services:
  db:
    image: postgres:15
    environment:
    - POSTGRES_DB=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  odoo:
    image: odoo:17.0
    depends_on:
    - db
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=odoo
    - DB_PASSWORD=root123
    - TZ=Europe/Paris
    ports:
    - "8069:8069"
    volumes:
    - ./odoo-data:/var/lib/odoo
    - ./addons:/mnt/extra-addons


  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
    - db
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@example.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - "5050:80"
    volumes:
    - ./pgadmin-data:/var/lib/pgadmin
